import { aiCostCalculatorExamples } from "../aiCostCalculatorExamples";

function localizeExamples(lang) {
    return aiCostCalculatorExamples.map((example) => ({
        title: example.title[lang],
        description: example.description[lang],
        href: `/en/ai-cost-calculator?${new URLSearchParams({
            inputTokens: String(example.params.inputTokens),
            outputTokens: String(example.params.outputTokens),
            requestsPerDay: String(example.params.requestsPerDay),
            preset: example.params.preset,
        }).toString()}`,
    }));
}

const faqItems = [
    {
        question: "How is the AI cost calculated?",
        answer:
            "The calculator multiplies input tokens by the model's input price and output tokens by the model's output price, using public per-million-token pricing. The result is then multiplied by the number of requests per day to estimate daily and monthly usage costs.",
    },
    {
        question: "Are the prices always up to date?",
        answer:
            "No. Prices can change frequently and providers may apply special rates for cached tokens, batch jobs, enterprise contracts or regional billing. Treat the result as an estimate and always verify current pricing on the provider's official pricing page before making business decisions.",
    },
    {
        question: "Why are input and output tokens priced differently?",
        answer:
            "Many LLM providers charge different prices for tokens sent to the model (input/prompt tokens) and tokens generated by the model (output/completion tokens). Output tokens are typically more expensive because they require computation-intensive generation work during inference.",
    },
    {
        question: "Can I use this with the Token Estimator?",
        answer:
            "Yes. First use the Token Estimator to count how many tokens your prompt or text uses, then enter those values here to estimate the cost of running that workload through an AI model like GPT-4, Claude or Gemini.",
    },
    {
        question: "How much does it cost to use the OpenAI API?",
        answer:
            "OpenAI API costs depend on the model you choose and how many tokens you process. For example, GPT-4o costs around $2.50 per million input tokens and $10 per million output tokens. Use this calculator to estimate your monthly spend based on your expected usage volume.",
    },
    {
        question: "What is the cheapest AI model for production use?",
        answer:
            "Budget-friendly models like GPT-4o mini, Claude Haiku and Gemini Flash offer the lowest per-token pricing while maintaining strong performance for many tasks. Select a model from the dropdown and adjust your expected usage to compare costs.",
    },
    {
        question: "How can I reduce my LLM API costs?",
        answer:
            "Common strategies include: choosing a smaller or cheaper model for simple tasks, reducing prompt length by removing unnecessary context, caching frequent responses, batching requests where possible, and using output token limits to control generation length.",
    },
];

const aiCostCalculatorEn = {
    lang: "en",
    locale: "en-US",
    currency: "USD",
    currentPath: "/en/ai-cost-calculator",
    toolKey: "aiCostCalculator",
    metadata: {
        title: "AI Cost Calculator",
        description:
            "Free AI cost calculator to estimate LLM API costs for OpenAI, Anthropic and Google models. Calculate cost per request, daily and monthly spend based on token usage.",
        intro: "Use this free AI cost calculator to estimate how much your AI API calls will cost across OpenAI, Anthropic and Google models. Enter input tokens, output tokens and expected daily requests to instantly calculate cost per request, daily spend and projected monthly cost. Compare pricing across GPT-4, Claude, Gemini and more.",
    },
    labels: {
        provider: "Provider",
        model: "Model",
        inputTokens: "Input tokens",
        outputTokens: "Output tokens",
        requestsPerDay: "Requests per day",
        results: {
            inputCost: "Input cost",
            outputCost: "Output cost",
            requestCost: "Cost per request",
            dailyCost: "Daily cost",
            monthlyCost: "Monthly cost",
        },
        pricingDisclaimerTitle: "Pricing disclaimer",
        pricingDisclaimer:
            "Prices are approximate and based on public per-million-token pricing. AI providers may change prices, apply volume discounts or use different pricing for cached tokens, batch APIs or regional billing. Always verify current pricing on the provider website before making production decisions.",
    },
    examples: localizeExamples("en"),
    faq: (
        <>
            {faqItems.map((item) => (
                <div key={item.question}>
                    <h3 className="mt-4 font-semibold">{item.question}</h3>
                    <p>{item.answer}</p>
                </div>
            ))}
        </>
    ),
    faqSchema: {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faqItems.map((item) => ({
            "@type": "Question",
            name: item.question,
            acceptedAnswer: {
                "@type": "Answer",
                text: item.answer,
            },
        })),
    },
    contextualTools: [
        {
            href: "/en/token-estimator",
            title: "Token Estimator",
            description:
                "Estimate how many tokens a prompt, text or JSON payload may use.",
        },
        {
            href: "/en/ai-cost-tools",
            title: "AI Cost Tools",
            description:
                "Overview of all AI cost estimation and token counting tools.",
        },
        {
            href: "/en/json-formatter",
            title: "JSON Formatter",
            description:
                "Format API payloads and model responses before estimating or debugging AI calls.",
        },
    ],
};

export default aiCostCalculatorEn;