

const aiCostCalculatorEn = {
    lang: "en",
    currentPath: "/en/ai-cost-calculator",
    locale: "en-US",
    metadata: {
        title: "AI Cost Calculator",
        description:
            "Estimate LLM API costs for OpenAI, Anthropic and Google models based on input tokens, output tokens and daily usage.",
        intro:
            "Use this AI cost calculator to estimate how much a prompt, API call or daily workload may cost across popular LLM providers. Enter input tokens, output tokens and expected requests per day to calculate estimated cost per request, daily cost and monthly cost.",
    },
    labels: {
        provider: "Provider",
        model: "Model",
        inputTokens: "Input tokens",
        outputTokens: "Output tokens",
        requestsPerDay: "Requests per day",
        results: {
            inputCost: "Input cost",
            outputCost: "Output cost",
            requestCost: "Cost per request",
            dailyCost: "Daily cost",
            monthlyCost: "Monthly cost",
        },
        pricingDisclaimerTitle: "Pricing disclaimer",
        pricingDisclaimer:
            "Prices are approximate and based on public per-million-token pricing. AI providers may change prices, apply volume discounts or use different pricing for cached tokens, batch APIs or regional billing. Always verify current pricing on the provider website before making production decisions.",
    },
    examples: [
        {
            title: "Estimate the cost of a chatbot",
            description:
                "Use average input and output tokens per conversation and multiply by the number of daily conversations.",
        },
        {
            title: "Compare models before shipping a feature",
            description:
                "Switch between providers and models to understand how model choice affects request, daily and monthly costs.",
        },
        {
            title: "Plan AI usage for a SaaS product",
            description:
                "Estimate how much a feature may cost when it is used hundreds or thousands of times per day.",
        },
    ],
    faq: (
        <>
            <h3 className="mt-4 font-semibold">How is the AI cost calculated?</h3>
            <p>
                The calculator multiplies input tokens by the model input price and output tokens
                by the model output price, using prices per one million tokens. The result is then
                multiplied by the number of requests per day to estimate daily and monthly usage.
            </p>

            <h3 className="mt-4 font-semibold">Are the prices always up to date?</h3>
            <p>
                No. Prices can change frequently and providers may apply special rates for cached
                tokens, batch jobs, enterprise contracts or regional billing. Treat the result as an
                estimate and check the official pricing page before making business decisions.
            </p>

            <h3 className="mt-4 font-semibold">Why are input and output tokens priced differently?</h3>
            <p>
                Many LLM providers charge different prices for tokens sent to the model and tokens
                generated by the model. Output tokens are often more expensive because they require
                generation work during inference.
            </p>

            <h3 className="mt-4 font-semibold">Can I use this with the Token Estimator?</h3>
            <p>
                Yes. First estimate how many tokens your prompt or text uses, then paste those values
                here to estimate the cost of running that workload through an AI model.
            </p>
        </>
    ),
    contextualTools: [
        {
            href: "/en/token-estimator",
            title: "Token Estimator",
            description:
                "Estimate how many tokens a prompt, text or JSON payload may use.",
        },
        {
            href: "/en/json-formatter",
            title: "JSON Formatter",
            description:
                "Format API payloads and model responses before estimating or debugging AI calls.",
        },
        {
            href: "/en/jwt-decoder",
            title: "JWT Encoder / Decoder",
            description:
                "Decode or generate JWT tokens when testing authenticated AI and API workflows.",
        },
    ],
};

export default aiCostCalculatorEn;