export const conversions = [
    {
        slug: "cm-a-pollici",
        from: "cm",
        to: "in",
        fromLabel: "centimetri",
        toLabel: "pollici",
        category: "length",
    },
    {
        slug: "pollici-a-cm",
        from: "in",
        to: "cm",
        fromLabel: "pollici",
        toLabel: "centimetri",
        category: "length",
    },
    {
        slug: "kg-a-libbre",
        from: "kg",
        to: "lb",
        fromLabel: "chilogrammi",
        toLabel: "libbre",
        category: "mass",
    },
    {
        slug: "libbre-a-kg",
        from: "lb",
        to: "kg",
        fromLabel: "libbre",
        toLabel: "chilogrammi",
        category: "mass",
    },
    {
        slug: "celsius-a-fahrenheit",
        from: "C",
        to: "F",
        fromLabel: "gradi Celsius",
        toLabel: "gradi Fahrenheit",
        category: "temperature",
    },
    {
        slug: "kmh-a-mph",
        from: "kmh",
        to: "mph",
        fromLabel: "km/h",
        toLabel: "mph",
        category: "speed",
    },
    {
        slug: "mph-a-kmh",
        from: "mph",
        to: "kmh",
        fromLabel: "mph",
        toLabel: "km/h",
        category: "speed",
    },
    {
        slug: "fahrenheit-a-celsius",
        from: "F",
        to: "C",
        fromLabel: "gradi Fahrenheit",
        toLabel: "gradi Celsius",
        category: "temperature",
    },
    {
        slug: "litri-a-galloni",
        from: "L",
        to: "gal_us",
        fromLabel: "litri",
        toLabel: "galloni",
        category: "volume",
    },
    {
        slug: "galloni-a-litri",
        from: "gal_us",
        to: "L",
        fromLabel: "galloni",
        toLabel: "litri",
        category: "volume",
    },
    {
        slug: "metri-a-piedi",
        from: "m",
        to: "ft",
        fromLabel: "metri",
        toLabel: "piedi",
        category: "length",
    },
    {
        slug: "piedi-a-metri",
        from: "ft",
        to: "m",
        fromLabel: "piedi",
        toLabel: "metri",
        category: "length",
    },
    {
        slug: "km-a-miglia",
        from: "km",
        to: "mi",
        fromLabel: "chilometri",
        toLabel: "miglia",
        category: "length",
    },
    {
        slug: "miglia-a-km",
        from: "mi",
        to: "km",
        fromLabel: "miglia",
        toLabel: "chilometri",
        category: "length",
    },
    {
        slug: "bar-a-psi",
        from: "bar",
        to: "psi",
        fromLabel: "bar",
        toLabel: "psi",
        category: "pressure",
    },
    {
        slug: "psi-a-bar",
        from: "psi",
        to: "bar",
        fromLabel: "psi",
        toLabel: "bar",
        category: "pressure",
    }
];
