export const conversions = [
    {
        slug: "cm-a-pollici",
        from: "cm",
        to: "in",
        fromLabel: "centimetri",
        toLabel: "pollici",
        category: "length",
    },
    {
        slug: "pollici-a-cm",
        from: "in",
        to: "cm",
        fromLabel: "pollici",
        toLabel: "centimetri",
        category: "length",
    },
    {
        slug: "kg-a-libbre",
        from: "kg",
        to: "lb",
        fromLabel: "chilogrammi",
        toLabel: "libbre",
        category: "mass",
    },
    {
        slug: "libbre-a-kg",
        from: "lb",
        to: "kg",
        fromLabel: "libbre",
        toLabel: "chilogrammi",
        category: "mass",
    },
    {
        slug: "celsius-a-fahrenheit",
        from: "C",
        to: "F",
        fromLabel: "gradi Celsius",
        toLabel: "gradi Fahrenheit",
        category: "temperature",
    },
    {
        slug: "kmh-a-mph",
        from: "kmh",
        to: "mph",
        fromLabel: "km/h",
        toLabel: "mph",
        category: "speed",
    },
];
