export const conversions = [
    {
        slug: "cm-a-pollici",
        from: "cm",
        to: "in",
        fromLabel: "centimetri",
        toLabel: "pollici",
        category: "length",
    },
    {
        slug: "pollici-a-cm",
        from: "in",
        to: "cm",
        fromLabel: "pollici",
        toLabel: "centimetri",
        category: "length",
    },
    {
        slug: "kg-a-libbre",
        from: "kg",
        to: "lb",
        fromLabel: "chilogrammi",
        toLabel: "libbre",
        category: "mass",
    },
    {
        slug: "libbre-a-kg",
        from: "lb",
        to: "kg",
        fromLabel: "libbre",
        toLabel: "chilogrammi",
        category: "mass",
    },
    {
        slug: "celsius-a-fahrenheit",
        from: "C",
        to: "F",
        fromLabel: "gradi Celsius",
        toLabel: "gradi Fahrenheit",
        category: "temperature",
    },
    {
        slug: "kmh-a-mph",
        from: "kmh",
        to: "mph",
        fromLabel: "km/h",
        toLabel: "mph",
        category: "speed",
    },
    {
        slug: "mph-a-kmh",
        from: "mph",
        to: "kmh",
        fromLabel: "mph",
        toLabel: "km/h",
        category: "speed",
    },
    {
        slug: "fahrenheit-a-celsius",
        from: "F",
        to: "C",
        fromLabel: "gradi Fahrenheit",
        toLabel: "gradi Celsius",
        category: "temperature",
    },
    {
        slug: "litri-a-galloni",
        from: "L",
        to: "gal",
        fromLabel: "litri",
        toLabel: "galloni",
        category: "volume",
    },
    {
        slug: "galloni-a-litri",
        from: "gal",
        to: "L",
        fromLabel: "galloni",
        toLabel: "litri",
        category: "volume",
    },
    {
        slug: "metri-a-piedi",
        from: "m",
        to: "ft",
        fromLabel: "metri",
        toLabel: "piedi",
        category: "length",
    },
    {
        slug: "piedi-a-metri",
        from: "ft",
        to: "m",
        fromLabel: "piedi",
        toLabel: "metri",
        category: "length",
    },
    {
        slug: "km-a-miglia",
        from: "km",
        to: "mi",
        fromLabel: "chilometri",
        toLabel: "miglia",
        category: "length",
    },
    {
        slug: "miglia-a-km",
        from: "mi",
        to: "km",
        fromLabel: "miglia",
        toLabel: "chilometri",
        category: "length",
    },
    {
        slug: "bar-a-psi",
        from: "bar",
        to: "psi",
        fromLabel: "bar",
        toLabel: "psi",
        category: "pressure",
    },
    {
        slug: "psi-a-bar",
        from: "psi",
        to: "bar",
        fromLabel: "psi",
        toLabel: "bar",
        category: "pressure",
    },
    {
        slug: "litri-a-ml",
        from: "L",
        to: "mL",
        fromLabel: "litri",
        toLabel: "millilitri",
        category: "volume",
    },
    {
        slug: "ml-a-litri",
        from: "mL",
        to: "L",
        fromLabel: "millilitri",
        toLabel: "litri",
        category: "volume",
    },
    {
        slug: "ms-a-kmh",
        from: "mps",
        to: "kmh",
        fromLabel: "m/s",
        toLabel: "km/h",
        category: "speed",
    },
    {
        slug: "kmh-a-ms",
        from: "kmh",
        to: "mps",
        fromLabel: "km/h",
        toLabel: "m/s",
        category: "speed",
    },
    {
        slug: "kg-a-oz",
        from: "kg",
        to: "oz",
        fromLabel: "chilogrammi",
        toLabel: "once",
        category: "mass",
    },
    {
        slug: "oz-a-kg",
        from: "oz",
        to: "kg",
        fromLabel: "once",
        toLabel: "chilogrammi",
        category: "mass",
    },
    {
        slug: "m2-a-ettari",
        from: "m2",
        to: "ha",
        fromLabel: "metri quadrati",
        toLabel: "ettari",
        category: "area",
    },
    {
        slug: "ettari-a-m2",
        from: "ha",
        to: "m2",
        fromLabel: "ettari",
        toLabel: "metri quadrati",
        category: "area",
    }
];
